name = "SpinGlass"
defaultTargets = ["SpinGlass"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"

[[require]]
name = "LeanArchitect"
git = "https://github.com/hanwenzhu/LeanArchitect.git"
rev = "main"

[[lean_lib]]
name = "SpinGlass"

[[lean_lib]]
name = "Common"

[[lean_lib]]
name = "GibbsMeasure"
