import SpinGlass.Cascades.Overlaps
import SpinGlass.ReplicaKernel
import Mathlib.Logic.Function.DependsOn
import Mathlib.Probability.Kernel.CondDistrib
import Mathlib.Probability.Kernel.Composition.CompNotation
import Mathlib.Probability.Kernel.Disintegration.Integral
import Mathlib.MeasureTheory.Function.ConditionalExpectation.PullOut

/-!
# Ghirlanda–Guerra identities

GG₁ as equalities under a replica law `μ` on `Fin (n+1) → β`, with prefix-measurable tests.
Main: `GG1`, `GG1Kernel`, `GG1_prefix_of_condExp_lastReplica_ae`. Talagrand Vol. II, Ch. 12.
-/

open MeasureTheory ProbabilityTheory
open scoped BigOperators ProbabilityTheory

namespace SpinGlass
namespace Cascades

section General

universe u
variable {β : Type u} [MeasurableSpace β]

/-! ## Prefix infrastructure -/

/-- Restrict an `(n+1)`-replica tuple to its first `n` coordinates. -/
def restrictReplicas (n : ℕ) (σs : Fin (n + 1) → β) : Fin n → β :=
  fun i => σs (Fin.castSucc i)

omit [MeasurableSpace β] in
@[simp] lemma restrictReplicas_apply (n : ℕ) (σs : Fin (n + 1) → β) (i : Fin n) :
    restrictReplicas (β := β) n σs i = σs (Fin.castSucc i) := rfl

/-! ### Prefix-measurable tests -/

/-- The set of indices corresponding to the first `n` replicas inside `Fin (n+1)`. -/
def firstSet (n : ℕ) : Set (Fin (n + 1)) :=
  Set.range (Fin.castSucc : Fin n → Fin (n + 1))

/-- Lift a test function on `n` replicas to a function on `n+1` replicas. -/
def liftTest (n : ℕ) (F : (Fin n → β) → ℝ) : (Fin (n + 1) → β) → ℝ :=
  fun σs => F (restrictReplicas (β := β) n σs)

omit [MeasurableSpace β] in
lemma dependsOn_liftTest (n : ℕ) (F : (Fin n → β) → ℝ) :
    DependsOn (liftTest (β := β) n F) (firstSet n) := by
  intro x y hxy
  have : restrictReplicas (β := β) n x = restrictReplicas (β := β) n y := by
    funext j
    apply hxy (Fin.castSucc j)
    exact ⟨j, rfl⟩
  simp [liftTest, this]

/-- Prefix σ-algebra on `(n+1)`-replica tuples, generated by the first `n` replicas. -/
def prefixMS (n : ℕ) : MeasurableSpace (Fin (n + 1) → β) :=
  (inferInstance : MeasurableSpace (Fin n → β)).comap (restrictReplicas (β := β) n)

lemma measurable_restrictReplicas_total (n : ℕ) : Measurable (restrictReplicas (β := β) n) := by
  classical
  refine measurable_pi_lambda _ (fun i => ?_)
  simpa [restrictReplicas] using (measurable_pi_apply (Fin.castSucc i))

lemma measurable_restrictReplicas (n : ℕ) :
    Measurable[prefixMS (β := β) n] (restrictReplicas (β := β) n) := by
  simpa [prefixMS] using (comap_measurable (restrictReplicas (β := β) n))

lemma measurable_liftTest (n : ℕ) {F : (Fin n → β) → ℝ} (hF : Measurable F) :
    Measurable[prefixMS (β := β) n] (liftTest (β := β) n F) := by
  simpa [liftTest] using hF.comp (measurable_restrictReplicas (β := β) n)

/-! ### Conditional law of the last replica -/

/-- The last replica coordinate `σ^{n+1}` as a function on `(n+1)`-replica tuples. -/
def lastReplica (n : ℕ) (σs : Fin (n + 1) → β) : β :=
  σs (Fin.last n)

omit [MeasurableSpace β] in
@[simp] lemma lastReplica_apply (n : ℕ) (σs : Fin (n + 1) → β) :
    lastReplica (β := β) n σs = σs (Fin.last n) := rfl

lemma measurable_lastReplica (n : ℕ) : Measurable (lastReplica (β := β) n) := by
  simpa [lastReplica] using (measurable_pi_apply (Fin.last n))

/-- Regular conditional law of the last replica given the first `n` replicas. -/
noncomputable def condDistribLast (n : ℕ) (μ : Measure (Fin (n + 1) → β))
    [IsFiniteMeasure μ] [StandardBorelSpace β] [Nonempty β] :
    ProbabilityTheory.Kernel (Fin n → β) β :=
  ProbabilityTheory.condDistrib (lastReplica (β := β) n) (restrictReplicas (β := β) n) μ

/-- Composing `condDistribLast` with the prefix law recovers the last-replica marginal. -/
lemma condDistribLast_comp_prefix (n : ℕ) (μ : Measure (Fin (n + 1) → β))
    [IsFiniteMeasure μ] [StandardBorelSpace β] [Nonempty β] :
    condDistribLast (β := β) n μ ∘ₘ (μ.map (restrictReplicas (β := β) n))
      =
      μ.map (lastReplica (β := β) n) := by
  have hX : AEMeasurable (restrictReplicas (β := β) n) μ :=
    (measurable_restrictReplicas_total (β := β) n).aemeasurable
  have hY : AEMeasurable (lastReplica (β := β) n) μ :=
    (measurable_lastReplica (β := β) n).aemeasurable
  simpa [condDistribLast, lastReplica] using
    (ProbabilityTheory.condDistrib_comp_map (X := restrictReplicas (β := β) n)
      (Y := lastReplica (β := β) n) (μ := μ) hX hY)

/-! ### Disintegration (integral form) -/

lemma integral_prefix_mul_condDistribLast (n : ℕ) (μ : Measure (Fin (n + 1) → β))
    [IsFiniteMeasure μ] [StandardBorelSpace β] [Nonempty β]
    {F : (Fin n → β) → ℝ} (hF : Measurable F) (hFbdd : ∃ C, ∀ x, ‖F x‖ ≤ C)
    {g : (Fin n → β) × β → ℝ} (hg : Measurable g) (hgbdd : ∃ C, ∀ p, ‖g p‖ ≤ C) :
    (∫ σs, F (restrictReplicas (β := β) n σs)
        * g (restrictReplicas (β := β) n σs, lastReplica (β := β) n σs) ∂μ)
      =
      ∫ x, F x * (∫ y, g (x, y) ∂condDistribLast (β := β) n μ x)
        ∂(μ.map (restrictReplicas (β := β) n)) := by
  classical
  -- Package `(prefix, last)` as a product measure `ρ`.
  let X : (Fin (n + 1) → β) → (Fin n → β) := restrictReplicas (β := β) n
  let Y : (Fin (n + 1) → β) → β := lastReplica (β := β) n
  let ρ : Measure ((Fin n → β) × β) := μ.map fun σs => (X σs, Y σs)

  let f : ((Fin n → β) × β) → ℝ := fun p => F p.1 * g p
  have hf_meas : Measurable f := by
    simpa [f] using (hF.comp measurable_fst).mul hg

  have hf_int : Integrable f ρ := by
    rcases hFbdd with ⟨CF, hCF⟩
    rcases hgbdd with ⟨Cg, hCg⟩
    have hbound : ∀ p : ((Fin n → β) × β), ‖f p‖ ≤ CF * Cg := by
      intro p
      have h1 : ‖F p.1‖ ≤ CF := hCF p.1
      have h2 : ‖g p‖ ≤ Cg := hCg p
      have hCF0 : 0 ≤ CF := le_trans (norm_nonneg _) h1
      calc
        ‖F p.1 * g p‖ ≤ ‖F p.1‖ * ‖g p‖ := norm_mul_le _ _
        _ ≤ CF * Cg := mul_le_mul h1 h2 (norm_nonneg _) hCF0
    haveI : IsFiniteMeasure ρ := by
      dsimp [ρ]
      infer_instance
    refine ⟨hf_meas.aestronglyMeasurable, ?_⟩
    exact HasFiniteIntegral.of_bounded (μ := ρ) (C := CF * Cg) (hC := ae_of_all ρ hbound)

  have hρ :
      (∫ x, ∫ y, f (x, y) ∂(ρ.condKernel x) ∂ρ.fst) = ∫ z, f z ∂ρ := by
    simpa using (MeasureTheory.Measure.integral_condKernel (ρ := ρ) (f := f) hf_int)

  have h_rhs :
      (∫ z, f z ∂ρ) =
        ∫ σs, F (X σs) * g (X σs, Y σs) ∂μ := by
    have hXY_meas : Measurable (fun σs => (X σs, Y σs)) :=
      (measurable_restrictReplicas_total (β := β) n).prodMk (measurable_lastReplica (β := β) n)
    have hXY_ae : AEMeasurable (fun σs => (X σs, Y σs)) μ := hXY_meas.aemeasurable
    have := (MeasureTheory.integral_map (μ := μ) (φ := fun σs => (X σs, Y σs)) hXY_ae
      (hfm := hf_int.1))
    simpa [ρ, f, X, Y] using this

  have hfst : ρ.fst = μ.map X := by
    have hYmeas : Measurable Y := by simpa [Y] using measurable_lastReplica (β := β) n
    simpa [ρ, X] using (Measure.fst_map_prodMk (X := X) (Y := Y) (μ := μ) hYmeas)

  have hcond : ρ.condKernel = condDistribLast (β := β) n μ := by
    simp [condDistribLast, ProbabilityTheory.condDistrib, ρ, X, Y]

  have h_lhs_simpl :
      (∫ x, ∫ y, f (x, y) ∂(ρ.condKernel x) ∂ρ.fst)
        =
      ∫ x, F x * (∫ y, g (x, y) ∂condDistribLast (β := β) n μ x)
        ∂(μ.map X) := by
    simp [hfst, hcond, f, integral_const_mul]

  calc
    (∫ σs, F (restrictReplicas (β := β) n σs)
        * g (restrictReplicas (β := β) n σs, lastReplica (β := β) n σs) ∂μ)
        = ∫ σs, F (X σs) * g (X σs, Y σs) ∂μ := by rfl
    _ = (∫ z, f z ∂ρ) := h_rhs.symm
    _ = (∫ x, ∫ y, f (x, y) ∂(ρ.condKernel x) ∂ρ.fst) := hρ.symm
    _ = ∫ x, F x * (∫ y, g (x, y) ∂condDistribLast (β := β) n μ x)
          ∂(μ.map X) := h_lhs_simpl
    _ = ∫ x, F x * (∫ y, g (x, y) ∂condDistribLast (β := β) n μ x)
          ∂(μ.map (restrictReplicas (β := β) n)) := by rfl

lemma integral_liftTest_mul_lastReplica (n : ℕ) (μ : Measure (Fin (n + 1) → β))
    [IsFiniteMeasure μ] [StandardBorelSpace β] [Nonempty β]
    {F : (Fin n → β) → ℝ} (hF : Measurable F) (hFbdd : ∃ C, ∀ x, ‖F x‖ ≤ C)
    {φ : β → ℝ} (hφ : Measurable φ) (hφbdd : ∃ C, ∀ y, ‖φ y‖ ≤ C) :
    (∫ σs, (liftTest (β := β) n F σs) * φ (lastReplica (β := β) n σs) ∂μ)
      =
      ∫ x, F x * (∫ y, φ y ∂condDistribLast (β := β) n μ x)
        ∂(μ.map (restrictReplicas (β := β) n)) := by
  -- specialize `integral_prefix_mul_condDistribLast` with `g (x,y) = φ y`
  have hg : Measurable (fun p : (Fin n → β) × β => φ p.2) := hφ.comp measurable_snd
  have hgbdd : ∃ C, ∀ p : (Fin n → β) × β, ‖(fun p => φ p.2) p‖ ≤ C := by
    rcases hφbdd with ⟨C, hC⟩
    refine ⟨C, ?_⟩
    intro p
    simpa using hC p.2
  simpa [liftTest] using
    (integral_prefix_mul_condDistribLast (β := β) (n := n) (μ := μ)
      (F := F) hF hFbdd (g := fun p : (Fin n → β) × β => φ p.2) hg hgbdd)

/-! ### Conditional expectation on the prefix σ-algebra -/

lemma condExp_prefix_ae_eq_integral_condDistribLast (n : ℕ) (μ : Measure (Fin (n + 1) → β))
    [IsFiniteMeasure μ] [StandardBorelSpace β] [Nonempty β]
    {g : (Fin n → β) × β → ℝ} (hg : Measurable g) (hgbdd : ∃ C, ∀ p, ‖g p‖ ≤ C) :
    μ[fun σs => g (restrictReplicas (β := β) n σs, lastReplica (β := β) n σs) | prefixMS (β := β) n]
      =ᵐ[μ]
        fun σs =>
          ∫ y, g (restrictReplicas (β := β) n σs, y)
            ∂condDistribLast (β := β) n μ (restrictReplicas (β := β) n σs) := by
  classical
  let X : (Fin (n + 1) → β) → (Fin n → β) := restrictReplicas (β := β) n
  let Y : (Fin (n + 1) → β) → β := lastReplica (β := β) n
  have hX : Measurable X := measurable_restrictReplicas_total (β := β) n
  have hY : AEMeasurable Y μ := (measurable_lastReplica (β := β) n).aemeasurable
  haveI : IsFiniteMeasure (μ.map fun σs => (X σs, Y σs)) := by infer_instance
  have hg_int : Integrable g (μ.map fun σs => (X σs, Y σs)) := by
    rcases hgbdd with ⟨C, hC⟩
    refine ⟨hg.aestronglyMeasurable, ?_⟩
    exact HasFiniteIntegral.of_bounded (μ := μ.map fun σs => (X σs, Y σs))
      (C := C) (hC := ae_of_all _ hC)
  simpa [prefixMS, condDistribLast, ProbabilityTheory.condDistrib, X, Y, lastReplica, restrictReplicas] using
    (ProbabilityTheory.condExp_prod_ae_eq_integral_condDistrib' (μ := μ)
      (X := X) (Y := Y) (f := fun p => g p) hX hY hg_int)

/-! ## Single-step GG identities -/

/-- GG₁ at level `n` for replica law `μ` on `Fin (n+1) → β`; the new replica is `Fin.last n`. -/
def GG1 (n : ℕ) (μ : Measure (Fin (n + 1) → β)) (R : β → β → ℝ) : Prop :=
  ∀ hn : n ≠ 0,
  ∀ (F : (Fin n → β) → ℝ),
    Measurable F →
    (∃ C, ∀ x, ‖F x‖ ≤ C) →
    (∃ C, ∀ x y, ‖R x y‖ ≤ C) →
      let i0 : Fin n := ⟨0, Nat.pos_of_ne_zero hn⟩
      (∫ σs, F (restrictReplicas (β := β) n σs) * R (σs 0) (σs (Fin.last n)) ∂μ)
        =
        (1 / (n : ℝ)) * (∫ σs, F (restrictReplicas (β := β) n σs) ∂μ)
            * (∫ σs, R (σs 0) (σs (Fin.succ i0)) ∂μ)
          +
        (1 / (n : ℝ)) *
          ((Finset.univ.erase i0).sum fun l : Fin n =>
            ∫ σs, F (restrictReplicas (β := β) n σs) * R (σs 0) (σs (Fin.castSucc l)) ∂μ)

/-- GG₁ quantified over tests measurable with respect to `prefixMS n`. -/
def GG1_prefix (n : ℕ) (μ : Measure (Fin (n + 1) → β)) (R : β → β → ℝ) : Prop :=
  ∀ hn : n ≠ 0,
  ∀ (G : (Fin (n + 1) → β) → ℝ),
    Measurable[prefixMS (β := β) n] G →
    (∃ C, ∀ x, ‖G x‖ ≤ C) →
    (∃ C, ∀ x y, ‖R x y‖ ≤ C) →
      let i0 : Fin n := ⟨0, Nat.pos_of_ne_zero hn⟩
      (∫ σs, G σs * R (σs 0) (σs (Fin.last n)) ∂μ)
        =
        (1 / (n : ℝ)) * (∫ σs, G σs ∂μ)
            * (∫ σs, R (σs 0) (σs (Fin.succ i0)) ∂μ)
          +
        (1 / (n : ℝ)) *
          ((Finset.univ.erase i0).sum fun l : Fin n =>
            ∫ σs, G σs * R (σs 0) (σs (Fin.castSucc l)) ∂μ)

/-! ## Bridges between formulations -/

lemma GG1_of_GG1_prefix {n : ℕ} {μ : Measure (Fin (n + 1) → β)} {R : β → β → ℝ} :
    GG1_prefix (β := β) n μ R → GG1 (β := β) n μ R := by
  intro hGG hn F hF hFbdd hRbdd
  have hmeas : Measurable[prefixMS (β := β) n] (liftTest (β := β) n F) :=
    measurable_liftTest (β := β) n (hF := hF)
  have hGbdd : (∃ C, ∀ x, ‖liftTest (β := β) n F x‖ ≤ C) := by
    rcases hFbdd with ⟨C, hC⟩
    refine ⟨C, ?_⟩
    intro x
    simpa [liftTest] using hC (restrictReplicas (β := β) n x)
  simpa [liftTest] using (hGG hn (liftTest (β := β) n F) hmeas hGbdd hRbdd)

/-! ### `GG1` for lifted tests -/
lemma GG1_liftTest {n : ℕ} {μ : Measure (Fin (n + 1) → β)} {R : β → β → ℝ}
    (hGG : GG1 (β := β) n μ R) {hn : n ≠ 0}
    (F : (Fin n → β) → ℝ) (hF : Measurable F)
    (hFbdd : ∃ C, ∀ x, ‖F x‖ ≤ C) (hRbdd : ∃ C, ∀ x y, ‖R x y‖ ≤ C) :
    let i0 : Fin n := ⟨0, Nat.pos_of_ne_zero hn⟩
    (∫ σs, (liftTest (β := β) n F σs) * R (σs 0) (σs (Fin.last n)) ∂μ)
      =
      (1 / (n : ℝ)) * (∫ σs, liftTest (β := β) n F σs ∂μ)
          * (∫ σs, R (σs 0) (σs (Fin.succ i0)) ∂μ)
        +
      (1 / (n : ℝ)) *
        ((Finset.univ.erase i0).sum fun l : Fin n =>
          ∫ σs, liftTest (β := β) n F σs * R (σs 0) (σs (Fin.castSucc l)) ∂μ) := by
  simpa [liftTest] using (hGG hn F hF hFbdd hRbdd)

/-- GG₁ for the pushforward law `κ ∘ₘ μ₀`. -/
def GG1Kernel {α : Type*} [MeasurableSpace α]
    (n : ℕ) (μ₀ : Measure α) [IsProbabilityMeasure μ₀]
    (κ : ProbabilityTheory.Kernel α (Fin (n + 1) → β)) [IsMarkovKernel κ]
    (R : β → β → ℝ) : Prop :=
  GG1 (β := β) n (κ ∘ₘ μ₀) R

/-! ## Conditional-expectation interface -/

lemma GG1_prefix_of_condExp_lastReplica_ae
    (n : ℕ) (μ : Measure (Fin (n + 1) → β)) (R : β → β → ℝ)
    [IsFiniteMeasure μ] :
    Measurable (fun p : β × β => R p.1 p.2) →
    (∀ hn : n ≠ 0,
      let i0 : Fin n := ⟨0, Nat.pos_of_ne_zero hn⟩
      μ[(fun σs : (Fin (n + 1) → β) => R (σs 0) (σs (Fin.last n))) | prefixMS (β := β) n]
        =ᵐ[μ]
          (fun σs : (Fin (n + 1) → β) =>
            (1 / (n : ℝ)) * (∫ τ : (Fin (n + 1) → β), R (τ 0) (τ (Fin.succ i0)) ∂μ)
              +
            (1 / (n : ℝ)) *
              ((Finset.univ.erase i0).sum fun l : Fin n =>
                R (σs 0) (σs (Fin.castSucc l))))) →
    GG1_prefix (β := β) n μ R := by
  intro hRmeas hCE hn G hG hGbdd hRbdd
  classical

  -- `prefixMS n ≤ ⊤` (i.e. ≤ the ambient measurable space)
  have hm : prefixMS (β := β) n ≤ (inferInstance : MeasurableSpace (Fin (n + 1) → β)) := by
    simpa [prefixMS] using (measurable_restrictReplicas_total (β := β) n).comap_le
  haveI : SigmaFinite (μ.trim hm) := by infer_instance

  let rLast : (Fin (n + 1) → β) → ℝ := fun σs => R (σs 0) (σs (Fin.last n))
  have hrLast_meas : Measurable rLast := by
    have hpair : Measurable fun σs : (Fin (n + 1) → β) => (σs 0, σs (Fin.last n)) := by
      exact (measurable_pi_apply (0 : Fin (n + 1))).prodMk (measurable_pi_apply (Fin.last n))
    simpa [rLast] using hRmeas.comp hpair

  have hG_meas_total : Measurable G := hG.mono hm le_rfl
  have hG_ae : AEStronglyMeasurable[prefixMS (β := β) n] G μ := hG.aestronglyMeasurable

  -- boundedness ⇒ integrability under a finite measure
  have hrLast_int : Integrable rLast μ := by
    rcases hRbdd with ⟨CR, hCR⟩
    refine ⟨hrLast_meas.aestronglyMeasurable, ?_⟩
    have hbound : ∀ σs, ‖rLast σs‖ ≤ CR := by
      intro σs
      simpa [rLast] using hCR (σs 0) (σs (Fin.last n))
    exact HasFiniteIntegral.of_bounded (μ := μ) (C := CR) (hC := ae_of_all μ hbound)

  have hG_int : Integrable G μ := by
    rcases hGbdd with ⟨CG, hCG⟩
    refine ⟨hG_meas_total.aestronglyMeasurable, ?_⟩
    exact HasFiniteIntegral.of_bounded (μ := μ) (C := CG) (hC := ae_of_all μ hCG)

  have hGrLast_int : Integrable (fun σs => G σs * rLast σs) μ := by
    rcases hGbdd with ⟨CG, hCG⟩
    rcases hRbdd with ⟨CR, hCR⟩
    have hmeas : Measurable (fun σs => G σs * rLast σs) := hG_meas_total.mul hrLast_meas
    refine ⟨hmeas.aestronglyMeasurable, ?_⟩
    have hbound : ∀ σs, ‖G σs * rLast σs‖ ≤ CG * CR := by
      intro σs
      have h1 : ‖G σs‖ ≤ CG := hCG σs
      have h2 : ‖rLast σs‖ ≤ CR := by
        simpa [rLast] using hCR (σs 0) (σs (Fin.last n))
      have hCG0 : 0 ≤ CG := le_trans (norm_nonneg _) h1
      calc
        ‖G σs * rLast σs‖ ≤ ‖G σs‖ * ‖rLast σs‖ := norm_mul_le _ _
        _ ≤ CG * CR := mul_le_mul h1 h2 (norm_nonneg _) hCG0
    exact HasFiniteIntegral.of_bounded (μ := μ) (C := CG * CR) (hC := ae_of_all μ hbound)

  -- Pull-out: `condExp (G * rLast | prefix) = G * condExp (rLast | prefix)`.
  have hpull :
      μ[(fun σs => G σs * rLast σs) | prefixMS (β := β) n]
        =ᵐ[μ] fun σs => G σs * μ[rLast | prefixMS (β := β) n] σs := by
    simpa [mul_assoc] using
      (MeasureTheory.condExp_mul_of_aestronglyMeasurable_left
        (μ := μ) (m := prefixMS (β := β) n) (f := G) (g := rLast)
        hG_ae hGrLast_int hrLast_int)

  -- Integrate `hpull` and use `integral_condExp` (law of total expectation).
  have hInt :
      (∫ σs, G σs * rLast σs ∂μ)
        =
      (∫ σs, G σs * (μ[rLast | prefixMS (β := β) n]) σs ∂μ) := by
    have hcondInt :
        (∫ σs, μ[(fun σs => G σs * rLast σs) | prefixMS (β := β) n] σs ∂μ)
          =
        (∫ σs, G σs * rLast σs ∂μ) := by
      simpa using
        (MeasureTheory.integral_condExp (μ := μ) (m := prefixMS (β := β) n) (m₀ := inferInstance)
          (f := fun σs => G σs * rLast σs) hm)
    calc
      (∫ σs, G σs * rLast σs ∂μ)
          = (∫ σs, μ[(fun σs => G σs * rLast σs) | prefixMS (β := β) n] σs ∂μ) := by
              simpa using hcondInt.symm
      _ = (∫ σs, (fun σs => G σs * μ[rLast | prefixMS (β := β) n] σs) σs ∂μ) := by
              refine integral_congr_ae ?_
              simpa using hpull
      _ = (∫ σs, G σs * (μ[rLast | prefixMS (β := β) n]) σs ∂μ) := by rfl

  -- Substitute the assumed a.e. formula for the conditional expectation.
  have hCE' := hCE hn
  let i0 : Fin n := ⟨0, Nat.pos_of_ne_zero hn⟩
  have hInt' :
      (∫ σs, G σs * (μ[rLast | prefixMS (β := β) n]) σs ∂μ)
        =
      (∫ σs,
          G σs *
            ((1 / (n : ℝ)) * (∫ τ : (Fin (n + 1) → β), R (τ 0) (τ (Fin.succ i0)) ∂μ)
              +
            (1 / (n : ℝ)) *
              ((Finset.univ.erase i0).sum fun l : Fin n =>
                R (σs 0) (σs (Fin.castSucc l))))
        ∂μ) := by
    refine integral_congr_ae ?_
    filter_upwards [hCE'] with σs hσs
    simpa [rLast, i0, mul_add, mul_assoc, mul_left_comm, mul_comm] using
      congrArg (fun t => G σs * t) hσs

  -- Expand the RHS integral into the `GG1_prefix` shape.
  -- Define shorthands for the constants and the finite sum.
  set a : ℝ :=
    (1 / (n : ℝ)) * (∫ τ : (Fin (n + 1) → β), R (τ 0) (τ (Fin.succ i0)) ∂μ)
  set s : Finset (Fin n) := Finset.univ.erase i0

  have hterm_int :
      ∀ l ∈ s, Integrable (fun σs => G σs * R (σs 0) (σs (Fin.castSucc l))) μ := by
    intro l hl
    rcases hGbdd with ⟨CG, hCG⟩
    rcases hRbdd with ⟨CR, hCR⟩
    have hpair : Measurable (fun σs : (Fin (n + 1) → β) => (σs 0, σs (Fin.castSucc l))) := by
      exact (measurable_pi_apply (0 : Fin (n + 1))).prodMk (measurable_pi_apply (Fin.castSucc l))
    have hRl_meas :
        Measurable (fun σs : (Fin (n + 1) → β) => R (σs 0) (σs (Fin.castSucc l))) := by
      simpa using hRmeas.comp hpair
    have hmeas :
        Measurable (fun σs : (Fin (n + 1) → β) => G σs * R (σs 0) (σs (Fin.castSucc l))) :=
      hG_meas_total.mul hRl_meas
    refine ⟨hmeas.aestronglyMeasurable, ?_⟩
    have hbound : ∀ σs, ‖G σs * R (σs 0) (σs (Fin.castSucc l))‖ ≤ CG * CR := by
      intro σs
      have h1 : ‖G σs‖ ≤ CG := hCG σs
      have h2 : ‖R (σs 0) (σs (Fin.castSucc l))‖ ≤ CR := hCR _ _
      have hCG0 : 0 ≤ CG := le_trans (norm_nonneg _) h1
      calc
        ‖G σs * R (σs 0) (σs (Fin.castSucc l))‖ ≤ ‖G σs‖ * ‖R (σs 0) (σs (Fin.castSucc l))‖ :=
          norm_mul_le _ _
        _ ≤ CG * CR := mul_le_mul h1 h2 (norm_nonneg _) hCG0
    exact HasFiniteIntegral.of_bounded (μ := μ) (C := CG * CR) (hC := ae_of_all μ hbound)

  have hsum :
      (∫ σs,
          G σs * ((1 / (n : ℝ)) * (s.sum fun l : Fin n =>
            R (σs 0) (σs (Fin.castSucc l))))
        ∂μ)
        =
      (1 / (n : ℝ)) *
        (s.sum fun l : Fin n =>
          ∫ σs, G σs * R (σs 0) (σs (Fin.castSucc l)) ∂μ) := by
    have :
        (fun σs : (Fin (n + 1) → β) =>
            G σs * (s.sum fun l : Fin n => R (σs 0) (σs (Fin.castSucc l))))
          =
        fun σs : (Fin (n + 1) → β) =>
          s.sum fun l : Fin n => (G σs * R (σs 0) (σs (Fin.castSucc l))) := by
      funext σs
      simp [Finset.mul_sum]
    have hint :
        (∫ σs, s.sum (fun l : Fin n => G σs * R (σs 0) (σs (Fin.castSucc l))) ∂μ)
          =
        s.sum fun l : Fin n => ∫ σs, G σs * R (σs 0) (σs (Fin.castSucc l)) ∂μ := by
      simpa using
        (MeasureTheory.integral_finset_sum (μ := μ) s
          (f := fun l : Fin n => fun σs => G σs * R (σs 0) (σs (Fin.castSucc l)))
          (hf := hterm_int))
    calc
      (∫ σs,
          G σs * ((1 / (n : ℝ)) * (s.sum fun l : Fin n =>
            R (σs 0) (σs (Fin.castSucc l))))
        ∂μ)
          =
        (1 / (n : ℝ)) *
          ∫ σs, (G σs * (s.sum fun l : Fin n => R (σs 0) (σs (Fin.castSucc l)))) ∂μ := by
            calc
              (∫ σs : (Fin (n + 1) → β),
                  G σs * ((1 / (n : ℝ)) * (s.sum fun l : Fin n =>
                    R (σs 0) (σs (Fin.castSucc l))))
                ∂μ)
                  =
                ∫ σs : (Fin (n + 1) → β),
                    (1 / (n : ℝ)) * (G σs * (s.sum fun l : Fin n =>
                      R (σs 0) (σs (Fin.castSucc l))))
                  ∂μ := by
                    refine integral_congr_ae ?_
                    filter_upwards with σs
                    ring_nf
              _ = (1 / (n : ℝ)) *
                    ∫ σs : (Fin (n + 1) → β),
                        (G σs * (s.sum fun l : Fin n =>
                          R (σs 0) (σs (Fin.castSucc l))))
                      ∂μ := by
                    simpa using
                      (MeasureTheory.integral_const_mul (μ := μ) (1 / (n : ℝ))
                        (fun σs : (Fin (n + 1) → β) =>
                          G σs * (s.sum fun l : Fin n =>
                            R (σs 0) (σs (Fin.castSucc l)))))
      _ = (1 / (n : ℝ)) *
            ∫ σs, s.sum (fun l : Fin n => G σs * R (σs 0) (σs (Fin.castSucc l))) ∂μ := by
              simp [this]
      _ = (1 / (n : ℝ)) *
            (s.sum fun l : Fin n =>
              ∫ σs, G σs * R (σs 0) (σs (Fin.castSucc l)) ∂μ) := by
              simp [hint]

  have hconst :
      (∫ σs, G σs * a ∂μ)
        =
      (1 / (n : ℝ)) * (∫ σs, G σs ∂μ) *
        (∫ τ : (Fin (n + 1) → β), R (τ 0) (τ (Fin.succ i0)) ∂μ) := by
    simp [a, mul_assoc, mul_left_comm, MeasureTheory.integral_mul_const]

  -- Final assembly.
  have hfinal :
      (∫ σs, G σs * rLast σs ∂μ)
        =
      (1 / (n : ℝ)) * (∫ σs, G σs ∂μ)
          * (∫ σs, R (σs 0) (σs (Fin.succ i0)) ∂μ)
        +
      (1 / (n : ℝ)) *
        ((Finset.univ.erase i0).sum fun l : Fin n =>
          ∫ σs, G σs * R (σs 0) (σs (Fin.castSucc l)) ∂μ) := by
    -- rewrite the RHS of `hInt'` using `a`/`s`, then split, then use `hconst`/`hsum`.
    have hInt'' :
        (∫ σs,
            G σs *
              (a + (1 / (n : ℝ)) * (s.sum fun l : Fin n =>
                R (σs 0) (σs (Fin.castSucc l))))
          ∂μ)
          =
        (∫ σs, G σs * a ∂μ)
          +
        (∫ σs,
            G σs * ((1 / (n : ℝ)) * (s.sum fun l : Fin n =>
              R (σs 0) (σs (Fin.castSucc l))))
          ∂μ) := by
      -- integrability comes from boundedness, already established above
      have h1 : Integrable (fun σs => G σs * a) μ := by
        rcases hGbdd with ⟨CG, hCG⟩
        refine ⟨(hG_meas_total.mul measurable_const).aestronglyMeasurable, ?_⟩
        have hbound : ∀ σs, ‖G σs * a‖ ≤ CG * ‖a‖ := by
          intro σs
          have h1' : ‖G σs‖ ≤ CG := hCG σs
          have hCG0 : 0 ≤ CG := le_trans (norm_nonneg _) h1'
          calc
            ‖G σs * a‖ ≤ ‖G σs‖ * ‖a‖ := norm_mul_le _ _
            _ ≤ CG * ‖a‖ := mul_le_mul h1' le_rfl (norm_nonneg _) hCG0
        exact HasFiniteIntegral.of_bounded (μ := μ) (C := CG * ‖a‖) (hC := ae_of_all μ hbound)
      have h2 :
          Integrable
            (fun σs => G σs * ((1 / (n : ℝ)) * (s.sum fun l : Fin n =>
              R (σs 0) (σs (Fin.castSucc l))))) μ := by
        rcases hGbdd with ⟨CG, hCG⟩
        rcases hRbdd with ⟨CR, hCR⟩
        -- boundedness is enough on a finite measure
        have hmeasSum :
            Measurable (fun σs : (Fin (n + 1) → β) =>
              s.sum fun l : Fin n => R (σs 0) (σs (Fin.castSucc l))) := by
          refine Finset.measurable_sum s (fun l hl => ?_)
          have hpair : Measurable (fun σs : (Fin (n + 1) → β) => (σs 0, σs (Fin.castSucc l))) := by
            exact (measurable_pi_apply (0 : Fin (n + 1))).prodMk (measurable_pi_apply (Fin.castSucc l))
          simpa using hRmeas.comp hpair
        have hmeas :
            Measurable (fun σs : (Fin (n + 1) → β) =>
              G σs * ((1 / (n : ℝ)) *
                (s.sum fun l : Fin n => R (σs 0) (σs (Fin.castSucc l))))) :=
          hG_meas_total.mul (measurable_const.mul hmeasSum)
        refine ⟨hmeas.aestronglyMeasurable, ?_⟩
        have hbound : ∀ σs,
            ‖G σs * ((1 / (n : ℝ)) * (s.sum fun l : Fin n => R (σs 0) (σs (Fin.castSucc l))))‖
              ≤ CG * (‖(1 / (n : ℝ))‖ * (s.card * CR)) := by
          intro σs
          have h1' : ‖G σs‖ ≤ CG := hCG σs
          have hCG0 : 0 ≤ CG := le_trans (norm_nonneg _) h1'
          have hsumR :
              ‖s.sum (fun l : Fin n => R (σs 0) (σs (Fin.castSucc l)))‖ ≤ s.card * CR := by
            have hnormsum :
                ‖s.sum (fun l : Fin n => R (σs 0) (σs (Fin.castSucc l)))‖
                  ≤ s.sum (fun l : Fin n => ‖R (σs 0) (σs (Fin.castSucc l))‖) := by
              simpa using norm_sum_le s (fun l => R (σs 0) (σs (Fin.castSucc l)))
            have hsum' :
                s.sum (fun l : Fin n => ‖R (σs 0) (σs (Fin.castSucc l))‖) ≤ s.card * CR := by
              have hterm : ∀ l ∈ s, ‖R (σs 0) (σs (Fin.castSucc l))‖ ≤ CR := by
                intro l hl
                exact hCR _ _
              have := Finset.sum_le_sum (fun l hl => hterm l hl)
              simpa [Finset.sum_const_nat] using this
            exact hnormsum.trans hsum'
          calc
            ‖G σs * ((1 / (n : ℝ)) * (s.sum fun l : Fin n => R (σs 0) (σs (Fin.castSucc l))))‖
                ≤ ‖G σs‖ * ‖(1 / (n : ℝ)) * (s.sum fun l : Fin n => R (σs 0) (σs (Fin.castSucc l)))‖ :=
                  norm_mul_le _ _
            _ ≤ ‖G σs‖ * (‖(1 / (n : ℝ))‖ * ‖s.sum (fun l : Fin n => R (σs 0) (σs (Fin.castSucc l)))‖) := by
                  gcongr
                  simp
            _ ≤ CG * (‖(1 / (n : ℝ))‖ * (s.card * CR)) := by
                  gcongr
        exact HasFiniteIntegral.of_bounded (μ := μ)
          (C := CG * (‖(1 / (n : ℝ))‖ * (s.card * CR))) (hC := ae_of_all μ hbound)
      simpa [mul_add, add_mul, mul_assoc] using (MeasureTheory.integral_add (μ := μ) h1 h2)
    -- now conclude
    have : (∫ σs, G σs * rLast σs ∂μ)
        =
        (∫ σs, G σs * a ∂μ)
          +
        (∫ σs,
            G σs * ((1 / (n : ℝ)) * (s.sum fun l : Fin n =>
              R (σs 0) (σs (Fin.castSucc l))))
          ∂μ) := by
      calc
        (∫ σs, G σs * rLast σs ∂μ)
            = (∫ σs, G σs * (μ[rLast | prefixMS (β := β) n]) σs ∂μ) := hInt
        _ = (∫ σs,
              G σs *
                (a + (1 / (n : ℝ)) * (s.sum fun l : Fin n =>
                  R (σs 0) (σs (Fin.castSucc l))))
            ∂μ) := by
              -- rewrite `hInt'` and unfold `a`, `s`
              simp [hInt', a, s]
        _ = (∫ σs, G σs * a ∂μ)
              +
            (∫ σs,
                G σs * ((1 / (n : ℝ)) * (s.sum fun l : Fin n =>
                  R (σs 0) (σs (Fin.castSucc l))))
              ∂μ) := hInt''
    -- rewrite with `hconst` and `hsum`, then unfold back `a`, `s`
    -- Keep rewriting controlled: `simp` was expanding `Finset.univ.erase` sums in an unhelpful way.
    -- We just rewrite the two integrals using `hconst`/`hsum` and unfold `rLast`, `a`, `s`.
    calc
      (∫ σs, G σs * rLast σs ∂μ)
          =
          (∫ σs, G σs * a ∂μ)
            +
          (∫ σs, G σs * ((1 / (n : ℝ)) * (s.sum fun l : Fin n =>
            R (σs 0) (σs (Fin.castSucc l)))) ∂μ) := this
      _ =
          (1 / (n : ℝ)) * (∫ σs, G σs ∂μ)
              * (∫ σs, R (σs 0) (σs (Fin.succ i0)) ∂μ)
            +
          (1 / (n : ℝ)) *
            (s.sum fun l : Fin n =>
              ∫ σs, G σs * R (σs 0) (σs (Fin.castSucc l)) ∂μ) := by
          -- `hconst`/`hsum` sometimes simplify `1 / (n : ℝ)` into `(↑n)⁻¹`; normalize explicitly.
          have hconst' :
              (∫ σs, G σs * a ∂μ)
                =
              (1 / (n : ℝ)) * (∫ σs, G σs ∂μ)
                  * (∫ σs, R (σs 0) (σs (Fin.succ i0)) ∂μ) := by
            simpa using hconst
          have hsum' :
              (∫ σs, G σs * ((1 / (n : ℝ)) * (s.sum fun l : Fin n =>
                    R (σs 0) (σs (Fin.castSucc l)))) ∂μ)
                =
              (1 / (n : ℝ)) *
                (s.sum fun l : Fin n =>
                  ∫ σs, G σs * R (σs 0) (σs (Fin.castSucc l)) ∂μ) := by
            simpa using hsum
          -- now rewrite and finish
          rw [hconst', hsum']
          -- goal solved by rewriting
      _ =
          (1 / (n : ℝ)) * (∫ σs, G σs ∂μ)
              * (∫ σs, R (σs 0) (σs (Fin.succ i0)) ∂μ)
            +
          (1 / (n : ℝ)) *
            ((Finset.univ.erase i0).sum fun l : Fin n =>
              ∫ σs, G σs * R (σs 0) (σs (Fin.castSucc l)) ∂μ) := by
          -- now just unfold `s`
          simp [s]

  simpa [rLast] using hfinal

end General

section SpinGlass

variable {N n : ℕ}
open SpinGlass.KernelBridge

/-- GG₁ specialized to SK overlaps on `(n+1)` replicas. -/
def SK_GG1 (N n : ℕ) (μ : Measure (ReplicaSpace N (n + 1))) : Prop :=
  GG1 (β := Config N) n μ (overlap N)

/-- The replica law induced by sampling `H ~ μH` then `n` Gibbs replicas given `H`. -/
noncomputable def gibbsReplicaLaw (N n : ℕ)
    (μH : Measure (EnergySpace N)) [IsProbabilityMeasure μH] :
    Measure (ReplicaSpace N n) :=
  (replicaGibbsKernel (N := N) (n := n)) ∘ₘ μH

/-- Kernel-level GG₁ specialized to the Gibbs replica sampler and a disorder law `μH`. -/
def SK_GG1_gibbsKernel (N n : ℕ)
    (μH : Measure (EnergySpace N)) [IsProbabilityMeasure μH] : Prop :=
  SK_GG1 (N := N) (n := n) (μ := gibbsReplicaLaw (N := N) (n := n + 1) μH)

end SpinGlass

end Cascades
end SpinGlass
