name: Build SpinGlass

on:
  push:
    branches: [main]
    paths:
      - '**/*.lean'
      - 'lean-toolchain'
      - 'lakefile.toml'
      - 'lake-manifest.json'
  pull_request:
    branches: [main]
    paths:
      - '**/*.lean'
      - 'lean-toolchain'
      - 'lakefile.toml'
      - 'lake-manifest.json'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_project:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Lean + mathlib cache
        uses: leanprover/lean-action@c544e89643240c6b398f14a431bcdc6309e36b3e # v1.4.0
        with:
          auto-config: false
          use-github-cache: false
          use-mathlib-cache: true

      - name: Cache .lake/build
        uses: actions/cache@v5
        with:
          path: .lake/build
          key: LakeBuild-${{ runner.os }}-${{ hashFiles('lean-toolchain') }}-${{ hashFiles('lake-manifest.json') }}
          restore-keys: LakeBuild-

      - name: Build
        run: ~/.elan/bin/lake build SpinGlass
